npmRegistries:
  "https://registry.yarnpkg.com":
    npmAlwaysAuth: true
  "https://npm.pkg.github.com":
    npmAuthToken: "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"
    npmAlwaysAuth: true

npmScopes:
  cosmoui:
    npmRegistryServer: "https://npm.pkg.github.com"
