name: Build

on:
  push:
    branches:
      - develop
      - "features/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install Dependencies
        run: yarn ci
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cosmoflex-artifact-dev
          path: dist

  check-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: cosmoflex-artifact-dev
