name: Build

on:
  push:
    branches:
      - master
      - develop
      - "features/*"
      - "hotfixs/*"
      - "releases/*"
      - "bugfixs/*"

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Get workflow version
        uses: actions/workflow-dispatch@v3
        with:
          workflow: version.yml
  build:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build Artifact
        run: yarn build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cosmoflex-artifact-dev
          path: dist
