name: Build

on:
  workflow_call:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: cosmoflex-version

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Artifact
        run: yarn build

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ./node_modules

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cosmoflex
          path: .
