name: Build

on:
  push:
    branches:
      - master
      - develop
      - "features/*"
      - "hotfixs/*"
      - "releases/*"
      - "bugfixs/*"

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Version dependencies
        uses: ./.github/workflows/version.yml
      - name: Uppload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cosomoflex-artifact
          path: ./
  build:
    needs:
      - jobs: version
    runs-on: ubuntu-latest
    steps:
      # - name: Version dependencies
      #   uses: ./.github/workflows/version.yml
      # - name: Download artifacts
      #   uses: actions/download-artifacts@v3
      #   with:
      #     name: cosmoflex-artifact
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build Artifact
        run: yarn build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cosmoflex-dist
          path: dist
