name: Build

on:
  workflow_call:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: cosmoflex-version

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm ci

      - name: Build Artifact
        run: pnpm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cosmoflex-build
          path: dist
