name: Build

on:
  workflow_run:
    workflows:
      - "Version"
    types:
      - completed
  push:
    branches:
      - develop
      - "features/*"
      - "hotfixs/*"
      - "releases/*"
      - "bugfixs/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build Artifact
        run: yarn build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cosmoflex-artifact-dev
          path: dist
