name: Build

on:
  workflow_call:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: cosmoflex-version
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build Artifact
        run: yarn build
      - name: Add .npmrc
        run: cp ./.npmrc dist/
      - name: List files
        run: ls dist
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cosmoflex-build
          path: dist
