name: Features

on:
  workflow_dispatch:
  push:
    branches:
      - "features/*"

permissions:
  contents: read
  packages: write

jobs:
  version:
    env:
      REGISTRY: https://npm.pkg.github.com
    uses: ./.github/workflows/version.yml
  build:
    needs: version
    uses: ./.github/workflows/build.yml
  publish:
    needs: build
    uses: ./.github/workflows/publish-github.yml
