name: Features

on:
  workflow_dispatch:
  push:
    branches:
      - "features/*"

jobs:
  version:
    uses: ./.github/workflows/version.yml
  build:
    needs: version
    uses: ./.github/workflows/build.yml
  publish:
    needs: build
    uses: ./.github/workflows/publish-github.yml
