name: Version

on:
  push:
    branches:
      - master
      - develop
      - "features/*"
      - "hotfixs/*"
      - "releases/*"
      - "bugfixs/*"

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Get last commit author
        run: |
          LAST_COMMIT=$(git log -1 --pretty=format:"%an|%ae")
          LAST_COMMIT_NAME=$(echo $LAST_COMMIT | cut -d '|' -f1)
          LAST_COMMIT_EMAIL=$(echo $LAST_COMMIT | cut -d '|' -f2)
      - name: Set Git Configuration
        run: |
          git config --global user.name "$LAST_COMMIT_NAME"
          git config --global user.email "$LAST_COMMIT_EMAIL"
      - name: Set Version
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [[ $BRANCH_NAME == "master" ]]; then
            VERSION=$(node -p "require('./package.json').version")
          elif [[ $BRANCH_NAME == "develop" ]]; then
            VERSION=$(node -p "require('./package.json').version")-beta-$(date +%s)
          elif [[ $BRANCH_NAME == "features/"* || $BRANCH_NAME == "hotfixs/"* ]]; then
            VERSION=$(node -p "require('./package.json').version")-alpha-$(date +%s)
          elif [[ $BRANCH_NAME == "releases/"* ]]; then
            VERSION=$(node -p "require('./package.json').version")-rc-$(date +%s)
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Update Version
        run: yarn version --new-version ${{ env.VERSION }}
      - run: ls
      - run: cat package.json
