name: Version

on:
  workflow_call:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Get last commit author
        run: |
          LAST_COMMIT=$(git log -1 --pretty=format:"%an|%ae")
          LAST_COMMIT_NAME=$(echo $LAST_COMMIT | cut -d '|' -f1)
          LAST_COMMIT_EMAIL=$(echo $LAST_COMMIT | cut -d '|' -f2)
          echo "COMMIT_NAME=$LAST_COMMIT_NAME" >> $GITHUB_ENV
          echo "COMMIT_EMAIL=$LAST_COMMIT_EMAIL" >> $GITHUB_ENV

      - name: Set Git Configuration
        run: |
          git config --global user.name ${{ env.COMMIT_NAME }}
          git config --global user.email ${{ env.COMMIT_EMAIL }}

      - name: Update Version
        shell: bash
        run: |
          yarn version --preminor alpha --preid=alpha.$(git rev-list --count --first-parent HEAD)

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cosmoflex-version
          path: ./
